### ISSUE TITLE
User Dashboard Nav

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/umrdr#105]
1. Please relabel 'New Work' button as 'Deposit Work'

2. Swap the location of ‘My Collections’ for ‘My Works’ (Order for Dashboard Nav should
be: Deposit Work | My Works | My Collections | Dashboard

3. Visibility of System Location ­ - @justcolin: Can we have a persistent white bar underneath the
current tab within the user dashboard? (This state change that was defined with
Trevor and Colin)

**Comment by respinos** [comment]
The most recent arrangement has the buttons divided between "top" and "bottom" so when the window narrows you get

![image](https://cloud.githubusercontent.com/assets/537867/13233118/323882b8-d980-11e5-93fd-08433cc585e9.png)

Does that change #2?

**Comment by respinos** [comment]
From @bnhowell: Let's stuff away the 'New Collection' option in the header.  I only had 'Deposit Work', 'My Works', 'My Collections', and 'Dashboard' in mind.

**Comment by justcolin** [comment]
@respinos: We'll just have to make sure there are two in the top div and two in the bottom. I can take care of this issue if you haven't already.

@bnhowell: Where do you want the create collection link? It has to be available somewhere because creating collections is part of the MVP currently. With all the other changes currently it doesn't have a convenient home.

**Comment by respinos** [comment]
re: yep, that's what my PR is doing.

You get "new collections" in the sidebar of "my works/collections". (But
yeah, nowhere else.)

-R

**Comment by justcolin** [comment]
@respinos @bnhowell: I want to get use of those buttons on the side since it is a little confusing that that is the only place you see them and they take up a lot of valuable real estate.

I'll remove the ads collection button from the header bar once we have a good home for it. Until then it is useful to have it up there for the people doing tests.

**Comment by bnhowell** [comment]
New Collections buttons appear in both 'My Works' and 'My Collections' pages. This is contextual and makes sense to users. 

Creating Collections within the list of works/collections satisfies MVP, no? (Or am I missing a requirement that it appear in a persistent header?)

**Comment by justcolin** [comment]
@bnhowell: That's fine if that's what you want, just wanted to check. Thanks!

**Comment by justcolin** [comment]
@bnhowell (on item 3) The triangle is there if you are currently on one of the pages. The little white triangle is being used instead of the white bar to distinguish it from the hover state.
