### ISSUE TITLE
link terms static page 

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#395]
![screen shot 2016-07-21 at 2 42 23 pm](https://cloud.githubusercontent.com/assets/3106478/17034605/73c8b7c4-4f51-11e6-8dfe-827301df26bc.png)

**Comment by njaffer** [comment]
The static page was created here: https://github.com/mlibrary/umrdr/pull/348 but not linked to agreement link

**Comment by njaffer** [comment]
@amyneeser, @grosscol: If we change the link for the deposit agreement to `http://localhost:3000/data/terms` instead of `http://localhost:3000/data/agreement`, we would loose the link to all the information on agreement page. I don't think there is another way to get to the agreement page with all the info about policy and terms of use

**Comment by amyneeser** [comment]
At the end of "for depositors" AND "for users" on this page https://staging.deepblue.lib.umich.edu/data/terms add: 

[View the full policy](https://staging.deepblue.lib.umich.edu/data/agreement)
