### ISSUE TITLE
Add grant number as metadata field 

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#399]
Multiple plain text fields.

**Comment by amyneeser** [comment]
Make this not required.

**Comment by njaffer** [comment]
Message from Matt C. "For a grant number, Dublin Core might not be the best option available.  It doesn't have a great fit, since Identifier is meant for the URI assigned to the dataset and the Relation qualifiers are designed more for bibliographic works.  They don't fit the characteristics of datasets very well.  There are a few options that might fit your needs, however.

1. The Data Documentation Initiative schema has a GrantNumber element.

2. The VIVO ontology has elements to capture grant information.  I've attached a PDF copy of the ontology's classes and properties.  If you take a look at the Grant class, it gives you the option of specifying if the grant number is a local grant number (i.e. one assigned by the Office of Research at UM) or the sponsor grant number (i.e. one assigned by the sponsoring institution or funding agency).

3. FRAPO, the Funding, Research Administration and Projects Ontology also has a predicate "has grant number" that might fit your needs."

RDS prefers option 1. Can be discussed more with Amy if needed.

**Comment by amyneeser** [comment]
Add two metadata fields: 
1. Funding Agency with drop down menu: 
National Science Foundation
National Institute of Health
DOE
DOD
DOT

Institute of Museum and Library Science 

2. ORSP Grant Number

**Comment by jrcarlso9** [comment]
More complete list of funding agencies to add based on the 2016 UMOR Annual Report on Research at UM: http://research.umich.edu/sites/default/files/resource-download/fy16_umor_annual_report_web.pdf
Centers for Disease Control and Prevention (CDC)
Department of Defense (DOD)
Department of Energy (DOE)
Department of Transportation (DOT)
National Aeronautics and Space Administration (NASA)
National Endowment for the Humanities (NEH) 
National Institutes of Health (NIH)
National Science Foundation (NSF)
Other Funding Agency (with a free text field next to the form for people to fill in the name of the agency or funding source)

**Comment by njaffer** [comment]
Add two metadata fields:

- [  ] Funding Agency with drop down menu:
[see Jake's list of funding agencies below]

- [  ] ORSP Grant Number
[blank field]

**Comment by amyneeser** [comment]
Do we need to ask Matt C. which metadata element to use for the funding agency?

**Comment by njaffer** [comment]
Left a message for Matt C. Waiting for his reply

**Comment by amyneeser** [comment]
Per Matt's e-mail:

**Comment by njaffer** [comment]
similar to : https://github.com/mlibrary/umrdr/blob/5b525d159cee8ecac9bc87f6e6bc9ead27a534b5/app/models/concerns/umrdr/generic_work_metadata.rb#L13

**Comment by amyneeser** [comment]
@njaffer From what we can tell, this is done. Do you need anything else from RDS?

**Comment by blancoj** [comment]
@amyneeser and @jakecarls Here is an image of what I have.  We can talk about it at our meeting Monday, but basically the user can only enter one grant number and one funding agency, and there is an issue with giving users a text area when they select other funding agency.  Here is what it looks like now:

<img width="1205" alt="screen shot 2017-03-17 at 3 53 29 pm" src="https://cloud.githubusercontent.com/assets/11095558/24060509/e7c98af6-0b29-11e7-9abc-a135e04b27f0.png">

**Comment by amyneeser** [comment]
@blancoj Here's the help text for these two fields: 

Funding agency: Select the agency funding your project from the list. 
ORSP grant number: Provide the grant number that the U-M's ORSP assigned to your project.

**Comment by njaffer** [comment]
Add another metadata field for 'other grant funding agency' as text

**Comment by blancoj** [comment]
The one thing that is left to do with this issue, is to add the "Other" option the ability to enter the name of the funding agency.
