### ISSUE TITLE
Remove full text extraction from derivatives generation

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#42]
The derivatives generation attempts to extract full text from pdfs and other document types.  Since we're not indexing the contents of datasets, this behavior needs to be turned off.

**Comment by grosscol** [comment]
Override `FileSet.create_derivatives` method.

**Comment by skorner** [comment]
It's certainly possible there was group consensus around not indexing full text from any content types, but I don't recall it and the MVP document was not updated to reflect it (hence #16). I'll bring it up in Steering tomorrow to make sure everyone is on the same page. Given the open issues with full text indexing in Sufia 7 and the dubious value in indexing most dataset content, this stance makes sense. However, some content types may be worth indexing, but that should be explored outside of the MVP in a controlled environment, IMO.

**Comment by skorner** [comment]
To close out the conversational aspect: Steering did recall the conversation to forgo full text indexing due to dubious value for datasets, but the docs were never updated to reflect this. We'll do that. This is all good.

There is interest in exploring full text extraction for tightly defined supplementary files that contain detailed descriptions of the dataset, or some aspect of it, but that's a feature request down the road.
