### ISSUE TITLE
Change "Citation" field in metadata to "Citation to related material"

### ISSUE THREAD

**Issue by jrcarlso9** [mlibrary/umrdr#449]
We should change the "Citation" field to something like "Citation to related material". The user is likely to assume it's a citation for the work itself, especially if what was entered is just a DOI: http://screencast.com/t/1Iusafi8

**Comment by billdueber** [comment]
The current abbreviated label is a change due to longer text not fitting in the "add a new row" button. The latest Sufia UI change pulls the "add" button down onto its own line where this won't be a problem, so we can just update the sufia gem and stop overriding the default gem behavior in conjunction with this text change.

**Comment by billdueber** [comment]
Closed: addressed by #484
