### ISSUE TITLE
visible draft works 

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#458]
I’m trying to upload draft works. I clicked the draft button and it is labeled as "visibility: draft” but it is showing in the live repo. I deleted what I uploaded because it is a real deposit for a faculty member. Could one of you check it out when you’re back in the office? I need to be able to do this ASAP.

<img width="630" alt="screen shot 2016-09-25 at 6 49 36 pm" src="https://cloud.githubusercontent.com/assets/3106478/18818773/de4e0bb6-8350-11e6-9c56-18e3eb1287ab.png">

**Comment by grosscol** [comment]
@amyneeser What you're seeing is expected behavior.  The visibility machinery is working from who has read access.  A user is able to discover any Works for which they have read access.  Since the owner has read access to all their own works (including drafts), they will show up in the owner's search results.  Additionally, any other user that has been granted edit access to a draft Work will have it show up in their search results.

The observed behavior would be considered a bug if another user who did not have, or was not expected to have read access, was seeing the draft work in their search results.
