### ISSUE TITLE
remove login prompt on "my works" page when logged in 

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#463]
When I am logged in and go to "my works" page, I see the message: "You need to sign in or sign up before continuing." Do not display this message when user is logged in. 

<img width="769" alt="screen shot 2016-10-04 at 4 54 20 pm" src="https://cloud.githubusercontent.com/assets/3106478/19092171/80946bc8-8a53-11e6-99cd-dd10c0ddbde2.png">

**Comment by skorner** [comment]
FYI, while working on this issue keep in mind the expected authn behavior that leverages the apache/cosign config: the app should be checking whether authentication is required for any given page and redirecting the user to `/data/login` if `X-Remote-User` isn't set.

**Comment by billdueber** [comment]
@botimer Just pinging Noah to make sure he sees the comment above.

**Comment by botimer** [comment]
Hmm... X-Remote-User because of mod_proxy, right?

Either way -- this matches my expectation. Pages that don't care can show guest/user content.

Pages that require a user should 401/302 to the protected login page with the "return to" URL set. This will pass without external redirect in case of an active Weblogin session (setting remote user), or shuttle off to Weblogin to create one, to be returned to this login page (which will mark the session as authenticated). Then the app should redirect to the initial page if set, or front/user page if the login page was hit with no referrer.

My instinct is that this message is an artifact of the flash message being set before the redirect and not getting purged on session creation/upgrade.
