### ISSUE TITLE
Form validation for deposit work

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#643]
## Background or Context
The existing deposit work form does not validate the data.

## Desired Behavior/Capability
Validate the data on entry and put a green check mark to show data entered is good.
- [ ] The creator field should have the format: Last name, First name MI
- [ ] Contact Information must be valid email address. 
- [ ] Year should be only numbers
- [ ] Keywords should not have commas

**Comment by jimeng** [comment]
Validating the creator field for all possible forms of names in the world may be difficult or impossible.  Can we assume that first names, last names and middle initials may contain any alphanumeric character plus spaces and certain punctuation marks (apostrophe, for example) and not other characters?  Also is middle initial required? Is first name required?

**Comment by njaffer** [comment]
Yeah we can start with that assumption. One rule we can apply is : validate  if it is  one word followed by  comma followed by another word like Jaffer,Nabeela

**Comment by jimeng** [comment]
My first thought about validating a creator name is that applications often have more success defining a class to represent a person (or some broader construct that includes people, organizations, corporations, etc) and then allow one of more instances of such a class for a concept like "creator".  That makes it easier to link multiple "creations" to the same "creator" without worry that some get lost due to typos in the name.  Can I assume that idea was discussed and discarded?

Are corporations and organizations not allowed as creators?

**Comment by njaffer** [comment]
No we did not discuss this idea. I think it would be good to discuss this more. May be in standup today?

**Comment by jimeng** [comment]
I meant to add to that last comment that if a creator (or other "person") is an instance of a class, input and output of the instance can be separated from the identity of the instance.  The format described here is likely needed in some context, but another format might be more appropriate in another context.

**Comment by jimeng** [comment]
## Validating the creator field
For creator field, search google for the wikipedia articles listing American, English, Spanish, French, Italian and Polish authors.  Find names in each list that use special characters, such as dashes, apostrophes, and various letters with accents and other marks.  Copy and paste names into the "creator" field, and submit the form.  Each of these names should fail to validate initially because they do not contain commas.  In each case, move the last name to the beginning and follow it immediately with a comma.  In that form, each of these names should validate.   Leading and trailing spaces should be ignored, except before the comma. Here are some examples of names that could be tested:

- Lucyna Ćwierczakiewiczowa **FAIL**
- Ćwierczakiewiczowa, Lucyna **VALID**
- Tadeusz Boy-Żeleński **FAIL**
- Boy-Żeleński, Tadeusz **VALID**

**Comment by jimeng** [comment]
## Validating contact information
The contact information field should accept a valid email address and reject anything that is not a valid emaIl address.

**Comment by jimeng** [comment]
## Validating year
The year should be four digits and nothing else.

**Comment by jimeng** [comment]
## Validating keywords field

**Comment by jimeng** [comment]
The validation for the creator field assumes a Latin alphabet.  Other characters will be needed going forward.  For now, names written in other alphabets (and possibly some names in Latin alphabets) will be rejected.
