### ISSUE TITLE
Appropriate redundancy for RDR services

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#647]

**Comment by skorner** [comment]
I know @botimer plans to comment on and refactor this issue, but it piques my curiosity enough to chime in early.

I'll focus first on "appropriate" rather than what redundancy we are talking about (application uptime or content preservation). It's unclear who is deciding what constitutes an appropriate level of redundancy, regardless of type, but I can say that DBD currently has the same application and data redundancy that Deep Blue has had for its over 10 years of existence. If DBD requires a higher level of redundancy, that's fine, but we should make it clear why.

Regarding data redundancy: 

DBD content is preserved with the same redundancy as all other UM Library repository content. There are two copies on spinning disk and two tape copies. All four copies are on infrastructure managed by central IT. This matches the current preservation strategy for DLXS collections and Deep Blue Data. Within our portfolio, only HathiTrust has a different architecture for the content.

The DBD application is hosted at one site, a high availability campus datacenter. This matches the hosting solution for Deep Blue. DLXS collections are hosted at two campus locations, but the underlying live content is still served from one campus location. In other words, the DLXS application is hosted at two sites, but the data is only live at a single site. The DBD and DB solutions require maintenance windows for basic server and application maintenance, as well as central IT maintenance on the underlying storage. This results in about two nines of uptime. Stepping up to the DLXS solution allows for non-disruptive server and application maintenance, which increases uptime to about three nines, at best. Any further gains in service uptime require true full stack redundancy that we do not provide for any UM-only repository services.

Increasing application availability to the level of DLXS has always been a goal of our Hydra-based solutions, but doing so with our canonical two-site solution is non-trivial. We may have better success achieving high availability within a single site through clustering. Quite a bit of R&D will be needed to determine and implement the right solution for out needs. When we tackle that issue, it will be generally for all our Hydra-based solutions.

**Comment by botimer** [comment]
Thanks, @skorner for all the info. I can't do any better than that. In the agile spirit, I think this is sufficient detail and doesn't reflect an immediate need for further work and documentation. If further needs emerge, we can record and prioritize them then.
