### ISSUE TITLE
hyrax - If file is bigger than 4Gig don't do virus checking (clamav)

### ISSUE THREAD

**Issue by blancoj** [mlibrary/umrdr#733]
Sebastien is investigating having storage check for virus independent of clamav.  This way we can upload large datasets.

**Comment by skorner** [comment]
After we left our meeting, a reason to ensure we leave virus checking on for small files ocurred to me. The current Fedora config stores "very small" files within the Fedora database rather than on disk. Thus, those very small files will not be scanned with any storage-system driven scanning.

In other words, there is a very good reason to keep proactively checking files up to a certain size using clamav. I'm not sure 4GB is the right threshold, given the memory issues in the default sufia/hyrax use of clamav. One option is to match it with the single-file self-deposit limit of 2GB.

**Comment by skorner** [comment]
I heard back from ITS Storage. They would have been willing to enable storage system-based virus scanning for me on our DBD NFS share, despite MiStorage only officially offering virus scanning for CIFS shares. However, what they use for AV adds nothing for us. They restrict scanning to only certain extensions (which are stripped in the Fedora storage of the file on disk anyway) and they cap the size at 100MB. Also, if there is a hit they simply zero out the file and log it in a security log for their consumption and not ours. You can see this AV service is designed to support a different use case than ours.

The only option for now (and probably for quite a while) is to disable scanning for any files bigger than X, where 0 < X <= 4GB. I'm fine with a 4GB limit if you can verify that a 4GB file can be scanned successfully without using a problematic amount of memory with the current implementation.

**Comment by amyneeser** [comment]
RDS will check with Jake about if we want to invest time to investigate how to run a separate virus check before ingest on large files.
