### ISSUE TITLE
Link to user profile from admin not working

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#753]
## Background or Context
From admin dashboard, click on stats. Click on a user.

![screen shot 2017-07-05 at 10 26 43 am](https://user-images.githubusercontent.com/12487929/27868978-7a73a9b6-616c-11e7-9055-6c5673612afc.png)

**Comment by njaffer** [comment]
Admin dashboard link: DBD_URL/admin

**Comment by jimeng** [comment]
This problem is in the hyrax 1.0.1 gem.  The link within the admin stats page to view a user's profile has an incorrect href.  The URL contains a user_key, which is an email address in most cases.  That seems to be true both in hyrax and in DBD.  In most places in hyrax where a user_key is included in a URL, it is escaped.  Any dots (periods) are replaced with the string '-dot-'.  But in that particular link, the email address is not escaped.  The result is the behavior described above. The error occurs in line 12 of this file: [samvera/hyrax/blob/v1.0.1/app/views/hyrax/admin/stats/_new_users.html.erb](https://github.com/samvera/hyrax/blob/v1.0.1/app/views/hyrax/admin/stats/_new_users.html.erb). The href attribute is rendered in this way: `<%= hyrax.profile_path(usr.user_key) %>`.  That could be fixed by passing the user object instead of the user_key attribute.

The problem seems to be fixed in the master branch of hyrax: [samvera/hyrax/blob/master/app/views/hyrax/admin/stats/_new_users.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/admin/stats/_new_users.html.erb), but it is not fixed in v1.0.2 or 1-0-stable.

**Comment by jimeng** [comment]
It appears that the problem was identified and fixed in hyrax in February:

`2379590487:hyrax jimeng$ git log app/views/hyrax/admin/stats/_new_users.html.erb
commit 4f8f06e898733793355082a24e55bc5cd84f4753
Author: Justin Coyne <jcoyne@justincoyne.com>
Date:   Thu Mar 2 19:39:02 2017 -0600

    Create links using User#to_param to escape dots in emails

commit ac89869759980a31458cc557a8c3afec7587882f
Author: Justin Coyne <jcoyne@justincoyne.com>
Date:   Tue Feb 28 11:43:22 2017 -0600

    Fix link to the user page

`
